# Generated by Django 5.1.2 on 2024-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_invoice_paymentattempt_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='ожидает оплату', max_length=20),
        ),
    ]
