# Generated by Django 5.1.2 on 2024-10-21 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
