# Generated by Django 5.1.2 on 2024-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_invoice_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
